name: gutterguard_flutter
description: "A Flutter mobile application project for GutterGuard devices."
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.6
  google_fonts: 6.1.0
  logger: ^2.0.2+1
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  logging: ^1.0.1
  connectivity_plus: ^6.0.1
  firebase_messaging: ^14.7.19
  provider: ^6.1.2
  location:
    git:
        url: https://github.com/781flyingdutchman/flutterlocation.git
        ref: V4
        path: packages/location
  rxdart: ^0.27.7
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/ic_gutterguard.png"
  # adaptive_icon_background: "#f7931e"

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
  assets:
   - assets/ic_notification_large.png
   - assets/ic_notification_small.png