// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, TargetPlatform;
  
const defaultTargetPlatform = TargetPlatform.android;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMamClOkwHXPfWjdYa64R1AIAQbuuPw1k',
    appId: '1:122381802302:web:5fe5ee41cca2f3fd55aa6f',
    messagingSenderId: '122381802302',
    projectId: 'dp-gutterguard',
    authDomain: 'dp-gutterguard.firebaseapp.com',
    databaseURL: 'https://dp-gutterguard-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dp-gutterguard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANoe0Ux7P2SkJxCzhPwdUu-QqcJPUyWJw',
    appId: '1:122381802302:android:51e52bf45042bac755aa6f',
    messagingSenderId: '122381802302',
    projectId: 'dp-gutterguard',
    databaseURL: 'https://dp-gutterguard-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dp-gutterguard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkcEFyTiT8mEkHz0KZTjKYKEqrUB3QgeQ',
    appId: '1:122381802302:ios:0cda659b642aa5cc55aa6f',
    messagingSenderId: '122381802302',
    projectId: 'dp-gutterguard',
    databaseURL: 'https://dp-gutterguard-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dp-gutterguard.appspot.com',
    iosBundleId: 'com.example.gutterguardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkcEFyTiT8mEkHz0KZTjKYKEqrUB3QgeQ',
    appId: '1:122381802302:ios:1189591d09df527555aa6f',
    messagingSenderId: '122381802302',
    projectId: 'dp-gutterguard',
    databaseURL: 'https://dp-gutterguard-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dp-gutterguard.appspot.com',
    iosBundleId: 'com.example.gutterguardFlutter.RunnerTests',
  );
}
